### ISSUE TITLE
Subtitles disappear when fast rewinding

### ISSUE THREAD

**Issue by thomasmattheussen** [osmc/osmc#186]
First of all, thanks for OSMC. Love it!

Don't know if this is a Kodi bug or OSMC one, but when I fast rewind (go back 30 secs) subtitles suddenly disappear. When I stop playback and then resume, subtitles are back. Happens every time.

**Comment by hessius** [comment]
Seeing this with the addon unpausejumpback as well. Can't replicate behaviour on 14.2 based SPMC on android which is all I have to compare with (but does seem to be an OSMC specific issue). I can get subtitles back by jumping back and then forward again as well.

**Comment by popcornmix** [comment]
Try disabling omxplayer in video/acceleration settings.
I believe this issue is fixed with the upcoming Isengard release.

**Comment by hessius** [comment]
That fixed the issue!

**Comment by maciex** [comment]
The problem still exists with latest version of OSMC (Auhust 2016 update).

**Comment by samnazarko** [comment]
This is quite an old issue. Try opening a forum post if you still have problems.
