### ISSUE TITLE
NOOBS/PINN mirror releases

### ISSUE THREAD

**Issue by procount** [osmc/osmc#536]
@samnazarko - We have a script that monitors new PINN OS releases that runs every day and notifies us of changes.
Are you aware that whenever you make a new OSMC release, we get notified for days that the release date has changed, then it's reverted, then it's updated, then reverted again.

For example, here are the last 3 notifications:

Sunday 10th Nov.
`os.json Release Date Change: OSMC_Pi1 - 2019-10-31 -> 2019-06-21`

Monday 11th November.
`os.json Release Date Change: OSMC_Pi1 - 2019-06-21 -> 2019-10-31`
`os.json Release Date Change: OSMC_Pi2 - 2019-10-31 -> 2019-06-21`

Tuesday 12th November
`os.json Release Date Change: OSMC_Pi2 - 2019-06-21 -> 2019-10-31`

I'm guessing maybe one of your mirrors is not getting updated in a timely manner.
The notifications are not a problem for us, but it does indicate that some of your users might not always be getting the latest release.

**Comment by samnazarko** [comment]
Hi @procount - thanks for the report.

Firstly, can you confirm the endpoint you are polling so I can ensure that you are hitting our mirror director correctly?

The mirror system redirects based on checksum and shouldn't be sending you to a stale mirror until it's synced. This is on a per file basis.

I can see from http://download.osmc.tv/installers/noobs/os-pi2.json?mirrorlist that all mirrors are synchronised. Can you confirm if this is still an issue?

It might be worth us serving small files (i.e. JSON) directly and saving the overhead of a redirect.

Cheers

**Comment by procount** [comment]
I can't be sure exactly because @matthuisman handles the scripts on his website but I'm sure he'll chime in if I get anything wrong.

Our main source is from http://downloads.raspberrypi.org/os_list_v3.json
Which currently links to your os.json files at:
"os_info": "http://download.osmc.tv/installers/noobs/os-pi1.json" and
"os_info": "http://download.osmc.tv/installers/noobs/os-pi2.json"

He reads those files, extracts the release date from them and compares them with a cached version from the last time he read the files (once a day). In this way we know when any of the remotely managed OSes have been updated, since the dates in http://downloads.raspberrypi.org/os_list_v3.json should really be kept up to date, but often aren't.

Since your last change on 31-10-19, we got notifications on 5th,6th,7th,10th,11th&12th Nov. I haven't had any more since then yet,, but I suppose it depends on which mirror it hits. 

Prior to that, we got notifications on:
18/9,17/9,27/8,26/8,13/8,12/8,9/8.

Looking at the history now, all those notifications oscillate between the current release date and 21/6, so it looks like you have one rogue mirror that hasn't been updated, or is updating very slowly.

(Maybe @matthuisman could try to identify which mirror is being slow at updating?)

Prior to that it still oscillated with notifications on:
26/6,24/6,9/5,8/5,5/5,4/5,25/4,12/4,

**Comment by samnazarko** [comment]
Thanks for the report. If this happens again, can you verify the checksum? This can be done with: http://download.osmc.tv/installers/noobs/os-pi2.json?sha256

If you can email me the IP you're polling from, I might be able to add some logging to see which mirrors you are being redirected to.

**Comment by matthuisman** [comment]
Just tried http://download.osmc.tv/installers/noobs/os-pi2.json a few times and eventually got redirected to below which still has old release date

**http://ftp.icm.edu.pl/pub/video/osmc/osmc/download/installers/noobs/os-pi2.json**
"release_date": "2019-06-21"

**Comment by samnazarko** [comment]
Thank you for your patience here.

I've performed some upgrades to our mirroring system. Can you check if the situation is now resolved?

Cheers

Sam

**Comment by procount** [comment]
Have you abandoned the mirror at edu.pl mentioned above, because it still has the old June date?

**Comment by matthuisman** [comment]
Just tried the URL a few times and got this
http://mirror.os6.org/osmc/osmc/download/installers/noobs/os-pi2.json

Old file as well. So looks like issue persists. Also the ?mirrorlist URL
seems to now be broken

**Comment by samnazarko** [comment]
Should be OK now. I'll fix the mirror page issue.
